export default {
    userName: "#user-name",
    password: "#password",
    loginBtn: "#login-button",
    titlepro: "//span[text()='Products']",
    dragndDrop: "//a[text()='Drag and Drop']",
    dragA: "#column-a",
    dragB: "#column-b",
    checkBox: "//a[text()='Checkboxes']",
    checkBoxes: "#checkboxes",
    scroll: "//a[text()='Infinite Scroll']",
    scroll1: "#content",
    search: "#searchbox-input",
    prPolicy: "//a[text()='Privacy Policy']",
    addndRemove: "//a[text()='Add/Remove Elements']",
    addButton: "//button ",
    delete: "//button[text()='Delete']",
    fileAppload: "//a[text()='File Upload']",
    chooseFile: "#file-upload",
    upload: "#file-submit",
    uploaded: "#uploaded-files",
    secureFile: "//a[text()='Secure File Download']",
    formAuthentication: "//a[text()='Form Authentication']",
    username1: "#username",
    userpswd: "#password",
    login: "//i",
    dropdown:"//a[text()='Dropdown']",
    downarrow:"#dropdown",
    option:"//option[text()='Option 1']",
    forgetpassword:"//a[text()='Forgot Password']",
    searchline:"#email",
    retrievebutton:"//i[text()='Retrieve password']",
    auth:"//a[text()='Basic Auth']",
    multiplewindows:"//a[text()='Multiple Windows']",
    clickhere:"//a[text()='Click Here']",
    notification:"//a[text()='Notification Messages']",
    clckhere:"//a[text()='Click here']",
    message:"#flash",
    rlink:"//a[text()='Redirect Link']",
    here:"#redirect",
    notfound:"//a[text()='404']"
   
};